### ISSUE TITLE
Are walls one tile wide or 0-width on the border between tiles?

### ISSUE THREAD

**Issue by Evelyn-H** [Evelyn-H/Multi-Agent-Surveillance#1]

**Comment by ellarauth** [comment]
i think making them one tile wide makes more sense because otherwise we run into issues when we want to visualize them on the map. they'd need to have a certain width when visualized, which might lead to it looking like our agents are running into objects while actually they aren't

**Comment by Evelyn-H** [comment]
Yeah, one tile width does make path finding a lot easier too, especially with regards to doors and windows
