### ISSUE TITLE
How do we represent structures?

### ISSUE THREAD

**Issue by Evelyn-H** [Evelyn-H/Multi-Agent-Surveillance#3]
Option one:
 - Have separate objects for `wall`s, `door`s and `window`s, each with a position (and other properties)
   - (maybe `door`s and `window`s could even be subclasses of `wall`)
 - Pros:
    - Easier to use for raycasting in vision
    - More uniform if  `door`s and `window`s are subclasses of `wall`

Option two:
 - Have one big object describing the whole structure

**Comment by ellarauth** [comment]
i think i'd go with option 1, that seems more flexible if we want to build different structures or alter some of them later

**Comment by Evelyn-H** [comment]
Agreed, it makes a lot of things easier
