### ISSUE TITLE
How do we implement vision?

### ISSUE THREAD

**Issue by Evelyn-H** [Evelyn-H/Multi-Agent-Surveillance#4]
Question #1: *What* does an agent see?
 - A wall as a line segment? just the fact that there is (or is not) a wall? something else?
 - Position of other agents? relative to itself or with global coordinates?

Guestion #2: How do we implement this?
 - raycasting...?

**Comment by ellarauth** [comment]
Question #1:
- i think an agent should see objects as the shape they have (or the part that's in its vision field)
- for the position of other agents and objects i think it might actually be useful to implement both, depending on what we want to do next block i could see both being useful

Question #2:
- i think raycasting sounds like the most reasonable thing to do
