### ISSUE TITLE
Noise

### ISSUE THREAD

**Issue by Evelyn-H** [Evelyn-H/Multi-Agent-Surveillance#6]

**Comment by Dexter192** [comment]
Can noise occur on stuctures?

**Comment by Evelyn-H** [comment]
> Can noise occur on stuctures?

Do you mean if a structure can be the source?

**Comment by Dexter192** [comment]
Structures should be able to be the source of a noise (opening doors, breaking wall)
I was referring to random noise. 
Lets say the area (0,0) to (25,25) should emit a noise event and (0,0) to (10,10) is structure. Can the random noise be on the structure e.g. (5,5)

**Comment by Evelyn-H** [comment]
Oh, yeah, sure

**Comment by Evelyn-H** [comment]
And I'd make the source always be the agent who opened the door and such, makes it easier to filter them out.
Then I'd make the random noises just have a source of `None`, cause the agent won't be able to see the source anyway

**Comment by Evelyn-H** [comment]
Also, in case you hadn't seen it, there's a basic `NoiseEvent` class in `simulation/communication.py` that encapsulates the event that will be received by the agents. Feel free to change it though

**Comment by Dexter192** [comment]
I will try to work with it. Probably at the weekend though

**Comment by Dexter192** [comment]
A Poisson Distribution of 0.1 events per minute is equal to an event every 10 minutes. With this code snippet we can compute the next time of an occuring event for each 25m^2 square:
`def nextTime():
    return -math.log(1.0 - random.random()) / 0.1`
We can scale this up to 6.4 events per minute in the whole map (for a 200x200 map) assuming each tile has a uniform distributed chance of emitting a noise event

A few testruns show (see picture), that it is poisson distributed and we only need to schedule a timer until the next event and then reset the timer with the next upcoming event 
![image](https://user-images.githubusercontent.com/15359953/53731783-1de62680-3e7c-11e9-9207-d6769d7ad1c7.png)

Implementation with the timer
![image](https://user-images.githubusercontent.com/15359953/53737530-12e7c200-3e8d-11e9-9d1e-5f9734ff8927.png)

Currently noise doesnt decay and only gets drawn when b is pressed

Source: https://preshing.com/20111007/how-to-generate-random-timings-for-a-poisson-process/

**Comment by Evelyn-H** [comment]
Okay, so I looked over the commit and added some feedback to it: https://github.com/Evelyn-H/Multi-Agent-Surveillance/commit/1866a519d8be5ee7ca2bd29479228f36cd962450

Please don't take any of it the wrong way, I'm genuinely just trying to help <3

**Comment by Evelyn-H** [comment]
Also just realised that you can get the correct distribution (poisson) by just triggering an event every frame with a certain chance. With the chance per frame being: `events_per_time_unit / frames_per_time_unit`.

**Comment by Dexter192** [comment]
I commited a new apporach to the random noise. If the direction is good I will add visualization etc. 
Also, I am unable to execute the code after rebasing it with the remote branch (I tested the noise part in a previous version. It should be unaffected by your changes)

**Comment by Evelyn-H** [comment]
Are you sure you pushed it? I can't see anything in the repo.
And did you rebase or merge? I'd recommend merging cause it makes it easier to track what changes happened when so it's easier to figure out problems when they occur.
